// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webhook4/webhook4.proto

/*
Package webhook4 is a generated protocol buffer package.

It is generated from these files:
	webhook4/webhook4.proto

It has these top-level messages:
	Retry
	Webhook
*/
package webhook4

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "bitbucket.org/subiz/servicespec/proto/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event int32

const (
	Event_Webhook4RetryCallback          Event = 0
	Event_Webhook4UpsertWebhookRequested Event = 1
	Event_Webhook4DeleteWebhookRequested Event = 2
	Event_Webhook4ReadWebhookRequested   Event = 3
	Event_Webhook4WebhookUpserted        Event = 4
	Event_Webhook4WebhookVerifyRequested Event = 5
)

var Event_name = map[int32]string{
	0: "Webhook4RetryCallback",
	1: "Webhook4UpsertWebhookRequested",
	2: "Webhook4DeleteWebhookRequested",
	3: "Webhook4ReadWebhookRequested",
	4: "Webhook4WebhookUpserted",
	5: "Webhook4WebhookVerifyRequested",
}
var Event_value = map[string]int32{
	"Webhook4RetryCallback":          0,
	"Webhook4UpsertWebhookRequested": 1,
	"Webhook4DeleteWebhookRequested": 2,
	"Webhook4ReadWebhookRequested":   3,
	"Webhook4WebhookUpserted":        4,
	"Webhook4WebhookVerifyRequested": 5,
}

func (x Event) Enum() *Event {
	p := new(Event)
	*p = x
	return p
}
func (x Event) String() string {
	return proto.EnumName(Event_name, int32(x))
}
func (x *Event) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Event_value, data, "Event")
	if err != nil {
		return err
	}
	*x = Event(value)
	return nil
}
func (Event) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Retry struct {
	Ctx              *common.Context `protobuf:"bytes,1,opt,name=ctx" json:"ctx,omitempty"`
	Partition        *string         `protobuf:"bytes,2,opt,name=partition" json:"partition,omitempty"`
	Queue            *string         `protobuf:"bytes,3,opt,name=queue" json:"queue,omitempty"`
	JobId            *string         `protobuf:"bytes,4,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	NBackoff         *int32          `protobuf:"varint,5,opt,name=n_backoff,json=nBackoff" json:"n_backoff,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Retry) Reset()                    { *m = Retry{} }
func (m *Retry) String() string            { return proto.CompactTextString(m) }
func (*Retry) ProtoMessage()               {}
func (*Retry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Retry) GetCtx() *common.Context {
	if m != nil {
		return m.Ctx
	}
	return nil
}

func (m *Retry) GetPartition() string {
	if m != nil && m.Partition != nil {
		return *m.Partition
	}
	return ""
}

func (m *Retry) GetQueue() string {
	if m != nil && m.Queue != nil {
		return *m.Queue
	}
	return ""
}

func (m *Retry) GetJobId() string {
	if m != nil && m.JobId != nil {
		return *m.JobId
	}
	return ""
}

func (m *Retry) GetNBackoff() int32 {
	if m != nil && m.NBackoff != nil {
		return *m.NBackoff
	}
	return 0
}

type Webhook struct {
	Ctx              *common.Context `protobuf:"bytes,1,opt,name=ctx" json:"ctx,omitempty"`
	ClientId         *string         `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Url              *string         `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Secret           *string         `protobuf:"bytes,4,opt,name=secret" json:"secret,omitempty"`
	IsEnabled        *bool           `protobuf:"varint,5,opt,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
	Events           []string        `protobuf:"bytes,6,rep,name=events" json:"events,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Webhook) Reset()                    { *m = Webhook{} }
func (m *Webhook) String() string            { return proto.CompactTextString(m) }
func (*Webhook) ProtoMessage()               {}
func (*Webhook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Webhook) GetCtx() *common.Context {
	if m != nil {
		return m.Ctx
	}
	return nil
}

func (m *Webhook) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *Webhook) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *Webhook) GetSecret() string {
	if m != nil && m.Secret != nil {
		return *m.Secret
	}
	return ""
}

func (m *Webhook) GetIsEnabled() bool {
	if m != nil && m.IsEnabled != nil {
		return *m.IsEnabled
	}
	return false
}

func (m *Webhook) GetEvents() []string {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Retry)(nil), "webhook4.Retry")
	proto.RegisterType((*Webhook)(nil), "webhook4.Webhook")
	proto.RegisterEnum("webhook4.Event", Event_name, Event_value)
}

func init() { proto.RegisterFile("webhook4/webhook4.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xc5, 0x9b, 0x4d, 0x49, 0x86, 0x03, 0x91, 0xc5, 0xb2, 0x81, 0x2e, 0x28, 0xf4, 0x54, 0x71,
	0x68, 0x24, 0xb4, 0x17, 0xae, 0x94, 0x1e, 0x7a, 0x8d, 0x04, 0x1c, 0xab, 0xd8, 0x99, 0x82, 0xdb,
	0xd4, 0x4e, 0x6d, 0xa7, 0xb4, 0x7c, 0x06, 0x9f, 0xc1, 0xbf, 0xf0, 0x4f, 0x28, 0xb1, 0xa3, 0x56,
	0xea, 0x85, 0xd3, 0xcc, 0x7b, 0xf3, 0xc6, 0xef, 0x8d, 0xe1, 0xfe, 0x27, 0xb2, 0x1f, 0x4a, 0x6d,
	0x1f, 0xf3, 0xa1, 0x99, 0x35, 0x5a, 0x59, 0x45, 0xa3, 0x01, 0xbf, 0xfe, 0xc8, 0x84, 0x65, 0x2d,
	0xdf, 0xa2, 0x9d, 0x29, 0xfd, 0x3d, 0x37, 0x2d, 0x13, 0xbf, 0x72, 0x83, 0xfa, 0x20, 0x38, 0x9a,
	0x06, 0x79, 0xde, 0x2f, 0xe4, 0x5c, 0xed, 0x76, 0x4a, 0xfa, 0xe2, 0x1e, 0x99, 0xfc, 0x26, 0x10,
	0x16, 0x68, 0xf5, 0x89, 0xbe, 0x83, 0x80, 0xdb, 0x63, 0x4a, 0x32, 0x32, 0x7d, 0xf6, 0xe1, 0xf9,
	0xcc, 0xab, 0xe6, 0x4a, 0x5a, 0x3c, 0xda, 0xa2, 0x9b, 0xd1, 0x07, 0x88, 0x9b, 0x52, 0x5b, 0x61,
	0x85, 0x92, 0xe9, 0x4d, 0x46, 0xa6, 0x71, 0x71, 0x26, 0xe8, 0x0b, 0x08, 0xf7, 0x2d, 0xb6, 0x98,
	0x06, 0xfd, 0xc4, 0x01, 0x7a, 0x07, 0xa3, 0x8d, 0x62, 0x2b, 0x51, 0xa5, 0xb7, 0x8e, 0xde, 0x28,
	0xb6, 0xac, 0xe8, 0x18, 0x62, 0xb9, 0x62, 0x25, 0xdf, 0xaa, 0xf5, 0x3a, 0x0d, 0x33, 0x32, 0x0d,
	0x8b, 0x48, 0x7e, 0x72, 0x78, 0xf2, 0x87, 0xc0, 0xd3, 0x6f, 0xee, 0xb8, 0xff, 0x89, 0x35, 0x86,
	0x98, 0xd7, 0x02, 0xa5, 0xed, 0x5c, 0x5c, 0xac, 0xc8, 0x11, 0xcb, 0x8a, 0x26, 0x10, 0xb4, 0xba,
	0xf6, 0x99, 0xba, 0x96, 0xbe, 0x84, 0x91, 0x41, 0xae, 0xd1, 0xfa, 0x44, 0x1e, 0xd1, 0x37, 0x00,
	0xc2, 0xac, 0x50, 0x96, 0xac, 0xc6, 0xaa, 0xcf, 0x14, 0x15, 0xb1, 0x30, 0x0b, 0x47, 0x74, 0x6b,
	0x78, 0x40, 0x69, 0x4d, 0x3a, 0xca, 0x82, 0x6e, 0xcd, 0xa1, 0xf7, 0x7f, 0x09, 0x84, 0x8b, 0xae,
	0xa5, 0xaf, 0xe0, 0xce, 0xa7, 0x7e, 0xec, 0xbf, 0x74, 0x5e, 0xd6, 0x75, 0x77, 0x62, 0xf2, 0x84,
	0x4e, 0xe0, 0xed, 0x30, 0xfa, 0xd2, 0x18, 0xd4, 0xd6, 0xa3, 0x02, 0xf7, 0x2d, 0x1a, 0x8b, 0x55,
	0x42, 0x2e, 0x35, 0x9f, 0xb1, 0x46, 0x8b, 0x57, 0x9a, 0x1b, 0x9a, 0xc1, 0xc3, 0xd9, 0xa2, 0xac,
	0xae, 0x14, 0x01, 0x1d, 0xc3, 0xfd, 0xa0, 0xf0, 0xd5, 0x19, 0x62, 0x95, 0xdc, 0x5e, 0x5a, 0xf8,
	0xfa, 0x15, 0xb5, 0x58, 0x9f, 0xce, 0x0f, 0x84, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x06, 0x9f,
	0xfb, 0x72, 0x70, 0x02, 0x00, 0x00,
}
