package header

func ListDefaultDefs() []*AttributeDefinition {
	return []*AttributeDefinition{
		&AttributeDefinition{
			Name:     "Google Analytics Client ID",
			Label:    "Google Analytics Client ID",
			Key:      "ga_client_id",
			Type:     "text",
			IsSystem: true,
		},
		&AttributeDefinition{
			Name:      "Banned",
			Label:     "Banned",
			I18NLabel: &I18NString{Vi_VN: "Bị chặn", En_US: "Banned"},
			Key:       "is_ban",
			Type:      "boolean",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:        "Avatar",
			Label:       "Ảnh đại diện",
			Description: "Ảnh cá nhân của người dùng",
			I18NLabel:   &I18NString{Vi_VN: "Ảnh đại diện", En_US: "Avatar"},
			Key:         "avatar_url",
			Type:        "text",
			IsImage:     true,
			IsSystem:    true,
		},
		&AttributeDefinition{
			// alway move forward
			Label:     "Bạn bè Zalo",
			I18NLabel: &I18NString{Vi_VN: "Bạn bè Zalo", En_US: "Zalo Friend Status"},
			Type:      "text",
			Select:    "dropdown",
			Items: []*AttributeDefinitionListItem{
				{Value: "stranger", I18NLabel: &I18NString{En_US: "Stranger", Vi_VN: "Người lạ"}, Label: "Người lạ"},
				{Value: "requested", I18NLabel: &I18NString{En_US: "Requested", Vi_VN: "Đã yêu cầu"}, Label: "Đã yêu cầu"},
				{Value: "requested_seen", I18NLabel: &I18NString{En_US: "Requseted and seen", Vi_VN: "Yêu cầu đã được xem"}, Label: "Yêu cầu đã được xem"},
				{Value: "being_requested", I18NLabel: &I18NString{En_US: "Being Requested", Vi_VN: "Đợi bạn phản hồi"}, Label: "Đợi bạn phản hồi"},
				{Value: "rejected", I18NLabel: &I18NString{En_US: "Rejected", Vi_VN: "Đã từ chối"}, Label: "Đã từ chối"},
				{Value: "being_rejected", I18NLabel: &I18NString{En_US: "Being Rejected", Vi_VN: "Bị từ chối"}, Label: "Bị từ chối"},
				{Value: "friend", I18NLabel: &I18NString{En_US: "Friend", Vi_VN: "Bạn bè"}, Label: "Bạn bè"},
			},
			Key: "zalo_friend_status",
		},
		&AttributeDefinition{
			Name:        "Đã theo dõi",
			Label:       "Đã theo dõi",
			Description: "Người dùng đã theo dõi Zalo OA hoặc Instagram",
			I18NLabel:   &I18NString{Vi_VN: "Đã theo dõi", En_US: "Is Followed"},
			Key:         "is_followed",
			Type:        "boolean",
			IsSystem:    true,
		},
		&AttributeDefinition{
			Name:        "Ẩn danh",
			Label:       "Ẩn danh",
			Description: "Người dùng ẩn danh trên Zalo",
			I18NLabel:   &I18NString{Vi_VN: "Ẩn danh", En_US: "Anonymous"},
			Key:         "is_anonymous",
			Type:        "boolean",
			IsSystem:    true,
		},
		&AttributeDefinition{
			Name:      "Timezone",
			Label:     "Timezone",
			I18NLabel: &I18NString{Vi_VN: "Múi giờ", En_US: "Timezone"},
			Key:       "timezone",
			Type:      "text",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:      "Email",
			Label:     "Email",
			I18NLabel: &I18NString{Vi_VN: "Email", En_US: "Email"},
			Key:       "emails",
			Type:      "text",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:      "Related Email",
			Label:     "Related Email",
			I18NLabel: &I18NString{Vi_VN: "Email liên quan", En_US: "Related Email"},
			Key:       "related_email",
			Type:      "text",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:      "Job title",
			Label:     "Job title",
			Key:       "job_title",
			I18NLabel: &I18NString{Vi_VN: "Chức danh", En_US: "Job title"},
			Type:      "text",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:      "Owner",
			Label:     "Lead owner",
			Key:       "owner",
			I18NLabel: &I18NString{Vi_VN: "Phụ trách", En_US: "Lead owner"},
			Type:      "text",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:       "Thời điểm phân lead",
			Label:      "Thời điểm phân lead",
			Key:        "lead_assigned_at",
			I18NLabel:  &I18NString{Vi_VN: "Thời điểm phân lead", En_US: "Lead assigned at"},
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&AttributeDefinition{
			Name:      "Ngày sinh",
			Label:     "Ngày sinh",
			Key:       "lead_assigned_at",
			I18NLabel: &I18NString{Vi_VN: "Ngày sinh", En_US: "Date of birth"},
			Type:      "datetime",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:      "Status",
			Label:     "Status",
			I18NLabel: &I18NString{Vi_VN: "Trạng thái", En_US: "Status"},
			Key:       "status",
			Type:      "text",
		},
		&AttributeDefinition{
			Name:        "Fullname",
			Label:       "Họ tên",
			Description: "Họ tên đầy đủ của người dùng",
			I18NLabel:   &I18NString{Vi_VN: "Họ tên", En_US: "Fullname"},
			Key:         "fullname",
			Type:        "text",
			IsSystem:    true,
		},
		&AttributeDefinition{
			Name:        "Display name",
			Label:       "Tên hiển thị",
			Description: "Tên hiển thị trên các nền tảng mạng xã hội",
			I18NLabel:   &I18NString{Vi_VN: "Tên hiển thị", En_US: "Display name"},
			Key:         "display_name",
			Type:        "text",
			IsSystem:    true,
		},
		&AttributeDefinition{
			Name:      "Address",
			Label:     "Address",
			I18NLabel: &I18NString{Vi_VN: "Địa chỉ", En_US: "Address"},
			Key:       "address",
			Type:      "text",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:      "City",
			Label:     "City",
			Key:       "city",
			Type:      "text",
			I18NLabel: &I18NString{Vi_VN: "Thành phố", En_US: "City"},
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:      "District",
			Label:     "District",
			I18NLabel: &I18NString{Vi_VN: "Quận/huyện", En_US: "District"},
			Key:       "district",
			Type:      "text",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:      "Phone",
			Label:     "Phone",
			I18NLabel: &I18NString{Vi_VN: "SĐT", En_US: "Phone"},
			Key:       "phones",
			Type:      "text",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:      "Related Phone",
			Label:     "Related Phone",
			I18NLabel: &I18NString{Vi_VN: "SĐT liên quan", En_US: "Related Phone Number"},
			Key:       "related_phone",
			Type:      "text",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:      "Focused",
			Label:     "Focused",
			I18NLabel: &I18NString{Vi_VN: "Đang xem", En_US: "Is focusing"},
			Key:       "focused",
			Type:      "boolean",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:      "Gender",
			Label:     "Gender",
			I18NLabel: &I18NString{Vi_VN: "Giới tính", En_US: "Gender"},
			Key:       "gender",
			Type:      "text",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:       "Created",
			Label:      "Created",
			Key:        "created",
			I18NLabel:  &I18NString{Vi_VN: "Tạo lúc", En_US: "Creation time"},
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&AttributeDefinition{
			Name:       "Modified",
			Label:      "Modified",
			I18NLabel:  &I18NString{Vi_VN: "Cập nhật lúc", En_US: "Modified at"},
			Key:        "modified",
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&AttributeDefinition{
			Name:       "Seen",
			Label:      "Hoạt động cuối",
			I18NLabel:  &I18NString{Vi_VN: "Hoạt động cuối", En_US: "Last seen"},
			Key:        "seen",
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&AttributeDefinition{
			Name:       "Total conversations",
			Label:      "Total conversations",
			Key:        "total_conversations",
			I18NLabel:  &I18NString{Vi_VN: "Tổng số hội thoại", En_US: "Total conversations"},
			Type:       "number",
			IsSystem:   true,
			IsReadonly: true,
		},
		&AttributeDefinition{
			Name:  "Last message sent time",
			Label: "Last message sent time",
			I18NLabel: &I18NString{
				Vi_VN: "Nhắn tin cuối lúc",
				En_US: "Last message sent time",
			},
			Key:        "last_message_sent",
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&AttributeDefinition{
			Name:  "Last order created at",
			Label: "Last Order Created At",
			I18NLabel: &I18NString{
				Vi_VN: "Thời điểm đơn tạo gần nhất",
				En_US: "Last order created at",
			},
			Key:        "last_order_at",
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&AttributeDefinition{
			Label:      "Thời gian tạo lead",
			I18NLabel:  &I18NString{Vi_VN: "Thời gian tạo lead", En_US: "Convert to lead at"},
			Type:       "datetime",
			Key:        "lead_at",
			IsSystem:   true,
			IsReadonly: true,
		},
		&AttributeDefinition{
			Label:     "Loại nguồn lead",
			I18NLabel: &I18NString{Vi_VN: "Loại nguồn lead", En_US: "Lead source type"},
			Type:      "text",
			Key:       "lead_source",
			IsSystem:  true,
		},
		&AttributeDefinition{
			// alway move forward
			Label:     "Giai đoạn vòng đời",
			I18NLabel: &I18NString{Vi_VN: "Giai đoạn vòng đời", En_US: "Lifecycle stage"},
			Type:      "text",
			Select:    "dropdown",
			Items: []*AttributeDefinitionListItem{
				{Value: "lead", I18NLabel: &I18NString{En_US: "Lead", Vi_VN: "Tiềm năng"}, Label: "Tiềm năng"},
				{Value: "trial", I18NLabel: &I18NString{En_US: "Trial", Vi_VN: "Dùng thử"}, Label: "Dùng thử"},
				{Value: "qualified lead", I18NLabel: &I18NString{En_US: "Sale Qualified", Vi_VN: "Chất lượng"}, Label: "Chất lượng"},
				{Value: "opportunity", I18NLabel: &I18NString{En_US: "Opportunity", Vi_VN: "Cơ hội"}, Label: "Cơ hội"},
				{Value: "customer", I18NLabel: &I18NString{En_US: "Customer", Vi_VN: "Khách hàng"}, Label: "Khách hàng"},
			},
			Key: "lifecycle_stage",
		},
		&AttributeDefinition{
			Label:      "Hành động tiếp lúc",
			I18NLabel:  &I18NString{Vi_VN: "Hành động tiếp lúc", En_US: "Next action at"},
			Type:       "datetime",
			Key:        "next_action_at",
			IsSystem:   true,
			IsReadonly: true,
		},
		&AttributeDefinition{
			Label:     "Nguồn lead",
			I18NLabel: &I18NString{Vi_VN: "Nguồn lead", En_US: "Lead source"},
			Type:      "text",
			Key:       "lead_source",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Label:     "Bạn của",
			I18NLabel: &I18NString{Vi_VN: "Bạn của", En_US: "Friend of"},
			Type:      "text",
			Key:       "friend_of",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:       "Tổng số đơn",
			Label:      "Tổng số đơn",
			I18NLabel:  &I18NString{Vi_VN: "Tổng số đơn", En_US: "Number of orders"},
			Key:        "num_orders",
			Type:       "number",
			IsSystem:   true,
			IsReadonly: true,
		},
		&AttributeDefinition{
			Label:       "Tổng giá trị đơn",
			Description: "Tổng giá trị các đơn đã xác nhận",
			I18NLabel:   &I18NString{Vi_VN: "Tổng giá trị đơn", En_US: "Total order value"},
			Type:        "number",
			Key:         "total_order_value",
			IsSystem:    true,
		},
		&AttributeDefinition{
			Name:       "First Interact",
			Label:      "First Interact",
			Key:        "first_interact",
			Type:       "text",
			I18NLabel:  &I18NString{Vi_VN: "Tương tác đầu tiên", En_US: "First interact"},
			IsSystem:   true,
			IsReadonly: true,
		},
		&AttributeDefinition{
			Name:      "Record ID",
			Label:     "Mã khách hàng",
			I18NLabel: &I18NString{Vi_VN: "Mã khách hàng", En_US: "Customer ID"},
			Key:       "record_id",
			Type:      "text",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:      "Unsubscribed marketing",
			Label:     "Unsubscribed marketing",
			I18NLabel: &I18NString{Vi_VN: "Không nhận tin marketing", En_US: "Unsubscribed"},
			Key:       "is_unsubscribed",
			Type:      "boolean",
			IsSystem:  true,
		},
		&AttributeDefinition{
			Name:  "Latest payment made time",
			Label: "Latest payment made time",
			I18NLabel: &I18NString{
				Vi_VN: "Thời thanh toán gần nhất",
				En_US: "Last payment made at",
			},
			Key:        "last_payment_made",
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&AttributeDefinition{
			Label:       "Tổng tiền đã thanh toán",
			Description: "Tổng tiền đã thanh toán",
			I18NLabel:   &I18NString{Vi_VN: "Tổng Tiền đã thanh toán", En_US: "Total payment made value"},
			Type:        "number",
			Key:         "total_payment_made",
			IsSystem:    true,
		},
	}
}
