# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webpush/webpush.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='webpush/webpush.proto',
  package='webpush',
  syntax='proto3',
  serialized_pb=_b('\n\x15webpush/webpush.proto\x12\x07webpush\"\x07\n\x05\x45mpty\"b\n\x05Token\x12\x11\n\tAccountId\x18\x01 \x01(\t\x12\x0e\n\x06UserId\x18\x02 \x01(\t\x12\r\n\x05Token\x18\x03 \x01(\t\x12\'\n\nDeviceType\x18\x05 \x01(\x0e\x32\x13.webpush.DeviceType\"F\n\x12TokenRemoveRequest\x12\x11\n\tAccountId\x18\x01 \x01(\t\x12\x0e\n\x06UserId\x18\x02 \x01(\t\x12\r\n\x05Token\x18\x03 \x01(\t\"\x9a\x01\n\x0bPushRequest\x12\x11\n\tAccountId\x18\x01 \x01(\t\x12\x0f\n\x07UserIds\x18\x02 \x03(\t\x12\'\n\nDeviceType\x18\x03 \x01(\x0e\x32\x13.webpush.DeviceType\x12\r\n\x05Title\x18\x04 \x01(\t\x12\x0c\n\x04\x42ody\x18\x05 \x01(\t\x12\x0c\n\x04Icon\x18\x06 \x01(\t\x12\x13\n\x0b\x43lickAction\x18\x07 \x01(\t\"A\n\x06Result\x12\x11\n\tAccountId\x18\x01 \x01(\t\x12\x0f\n\x07UserIds\x18\x02 \x03(\t\x12\x13\n\x0bSendSuccess\x18\x03 \x03(\x08*/\n\nDeviceType\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07\x42ROWSER\x10\x01\x12\n\n\x06MOBILE\x10\x02*a\n\x05\x45vent\x12\x18\n\x14WebpushRegisterToken\x10\x00\x12\x16\n\x12WebpushRemoveToken\x10\x02\x12\x0f\n\x0bWebpushPush\x10\x03\x12\x15\n\x11WebpushPushReturn\x10\x04\x32\xab\x01\n\x07Webpush\x12\x31\n\rRegisterToken\x12\x0e.webpush.Token\x1a\x0e.webpush.Empty\"\x00\x12<\n\x0bRemoveToken\x12\x1b.webpush.TokenRemoveRequest\x1a\x0e.webpush.Empty\"\x00\x12/\n\x04Push\x12\x14.webpush.PushRequest\x1a\x0f.webpush.Result\"\x00\x62\x06proto3')
)

_DEVICETYPE = _descriptor.EnumDescriptor(
  name='DeviceType',
  full_name='webpush.DeviceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BROWSER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=439,
  serialized_end=486,
)
_sym_db.RegisterEnumDescriptor(_DEVICETYPE)

DeviceType = enum_type_wrapper.EnumTypeWrapper(_DEVICETYPE)
_EVENT = _descriptor.EnumDescriptor(
  name='Event',
  full_name='webpush.Event',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WebpushRegisterToken', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WebpushRemoveToken', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WebpushPush', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WebpushPushReturn', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=488,
  serialized_end=585,
)
_sym_db.RegisterEnumDescriptor(_EVENT)

Event = enum_type_wrapper.EnumTypeWrapper(_EVENT)
NONE = 0
BROWSER = 1
MOBILE = 2
WebpushRegisterToken = 0
WebpushRemoveToken = 2
WebpushPush = 3
WebpushPushReturn = 4



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='webpush.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=41,
)


_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='webpush.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccountId', full_name='webpush.Token.AccountId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UserId', full_name='webpush.Token.UserId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Token', full_name='webpush.Token.Token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DeviceType', full_name='webpush.Token.DeviceType', index=3,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=141,
)


_TOKENREMOVEREQUEST = _descriptor.Descriptor(
  name='TokenRemoveRequest',
  full_name='webpush.TokenRemoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccountId', full_name='webpush.TokenRemoveRequest.AccountId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UserId', full_name='webpush.TokenRemoveRequest.UserId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Token', full_name='webpush.TokenRemoveRequest.Token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=213,
)


_PUSHREQUEST = _descriptor.Descriptor(
  name='PushRequest',
  full_name='webpush.PushRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccountId', full_name='webpush.PushRequest.AccountId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UserIds', full_name='webpush.PushRequest.UserIds', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DeviceType', full_name='webpush.PushRequest.DeviceType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Title', full_name='webpush.PushRequest.Title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Body', full_name='webpush.PushRequest.Body', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Icon', full_name='webpush.PushRequest.Icon', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ClickAction', full_name='webpush.PushRequest.ClickAction', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=370,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='webpush.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccountId', full_name='webpush.Result.AccountId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UserIds', full_name='webpush.Result.UserIds', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SendSuccess', full_name='webpush.Result.SendSuccess', index=2,
      number=3, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=437,
)

_TOKEN.fields_by_name['DeviceType'].enum_type = _DEVICETYPE
_PUSHREQUEST.fields_by_name['DeviceType'].enum_type = _DEVICETYPE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Token'] = _TOKEN
DESCRIPTOR.message_types_by_name['TokenRemoveRequest'] = _TOKENREMOVEREQUEST
DESCRIPTOR.message_types_by_name['PushRequest'] = _PUSHREQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.enum_types_by_name['DeviceType'] = _DEVICETYPE
DESCRIPTOR.enum_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'webpush.webpush_pb2'
  # @@protoc_insertion_point(class_scope:webpush.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), dict(
  DESCRIPTOR = _TOKEN,
  __module__ = 'webpush.webpush_pb2'
  # @@protoc_insertion_point(class_scope:webpush.Token)
  ))
_sym_db.RegisterMessage(Token)

TokenRemoveRequest = _reflection.GeneratedProtocolMessageType('TokenRemoveRequest', (_message.Message,), dict(
  DESCRIPTOR = _TOKENREMOVEREQUEST,
  __module__ = 'webpush.webpush_pb2'
  # @@protoc_insertion_point(class_scope:webpush.TokenRemoveRequest)
  ))
_sym_db.RegisterMessage(TokenRemoveRequest)

PushRequest = _reflection.GeneratedProtocolMessageType('PushRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUSHREQUEST,
  __module__ = 'webpush.webpush_pb2'
  # @@protoc_insertion_point(class_scope:webpush.PushRequest)
  ))
_sym_db.RegisterMessage(PushRequest)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'webpush.webpush_pb2'
  # @@protoc_insertion_point(class_scope:webpush.Result)
  ))
_sym_db.RegisterMessage(Result)



_WEBPUSH = _descriptor.ServiceDescriptor(
  name='Webpush',
  full_name='webpush.Webpush',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=588,
  serialized_end=759,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterToken',
    full_name='webpush.Webpush.RegisterToken',
    index=0,
    containing_service=None,
    input_type=_TOKEN,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveToken',
    full_name='webpush.Webpush.RemoveToken',
    index=1,
    containing_service=None,
    input_type=_TOKENREMOVEREQUEST,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Push',
    full_name='webpush.Webpush.Push',
    index=2,
    containing_service=None,
    input_type=_PUSHREQUEST,
    output_type=_RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEBPUSH)

DESCRIPTOR.services_by_name['Webpush'] = _WEBPUSH

# @@protoc_insertion_point(module_scope)
