// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package notibox

@SerialVersionUID(0L)
final case class AddNotificationRequest(
    ctx: scala.Option[common.Context] = None,
    boxs: _root_.scala.collection.Seq[_root_.scala.Predef.String] = _root_.scala.collection.Seq.empty,
    notification: scala.Option[notibox.Notification] = None
    ) extends scalapb.GeneratedMessage with scalapb.Message[AddNotificationRequest] with scalapb.lenses.Updatable[AddNotificationRequest] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      if (ctx.isDefined) { __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(ctx.get.serializedSize) + ctx.get.serializedSize }
      boxs.foreach(boxs => __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, boxs))
      if (notification.isDefined) { __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(notification.get.serializedSize) + notification.get.serializedSize }
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      ctx.foreach { __v =>
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__v.serializedSize)
        __v.writeTo(_output__)
      };
      boxs.foreach { __v =>
        _output__.writeString(2, __v)
      };
      notification.foreach { __v =>
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__v.serializedSize)
        __v.writeTo(_output__)
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): notibox.AddNotificationRequest = {
      var __ctx = this.ctx
      val __boxs = (_root_.scala.collection.immutable.Vector.newBuilder[_root_.scala.Predef.String] ++= this.boxs)
      var __notification = this.notification
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __ctx = Option(_root_.scalapb.LiteParser.readMessage(_input__, __ctx.getOrElse(common.Context.defaultInstance)))
          case 18 =>
            __boxs += _input__.readString()
          case 26 =>
            __notification = Option(_root_.scalapb.LiteParser.readMessage(_input__, __notification.getOrElse(notibox.Notification.defaultInstance)))
          case tag => _input__.skipField(tag)
        }
      }
      notibox.AddNotificationRequest(
          ctx = __ctx,
          boxs = __boxs.result(),
          notification = __notification
      )
    }
    def getCtx: common.Context = ctx.getOrElse(common.Context.defaultInstance)
    def clearCtx: AddNotificationRequest = copy(ctx = None)
    def withCtx(__v: common.Context): AddNotificationRequest = copy(ctx = Option(__v))
    def clearBoxs = copy(boxs = _root_.scala.collection.Seq.empty)
    def addBoxs(__vs: _root_.scala.Predef.String*): AddNotificationRequest = addAllBoxs(__vs)
    def addAllBoxs(__vs: TraversableOnce[_root_.scala.Predef.String]): AddNotificationRequest = copy(boxs = boxs ++ __vs)
    def withBoxs(__v: _root_.scala.collection.Seq[_root_.scala.Predef.String]): AddNotificationRequest = copy(boxs = __v)
    def getNotification: notibox.Notification = notification.getOrElse(notibox.Notification.defaultInstance)
    def clearNotification: AddNotificationRequest = copy(notification = None)
    def withNotification(__v: notibox.Notification): AddNotificationRequest = copy(notification = Option(__v))
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => ctx.orNull
        case 2 => boxs
        case 3 => notification.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => ctx.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => _root_.scalapb.descriptors.PRepeated(boxs.map(_root_.scalapb.descriptors.PString)(_root_.scala.collection.breakOut))
        case 3 => notification.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = notibox.AddNotificationRequest
}

object AddNotificationRequest extends scalapb.GeneratedMessageCompanion[notibox.AddNotificationRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[notibox.AddNotificationRequest] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): notibox.AddNotificationRequest = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    notibox.AddNotificationRequest(
      __fieldsMap.get(__fields.get(0)).asInstanceOf[scala.Option[common.Context]],
      __fieldsMap.getOrElse(__fields.get(1), Nil).asInstanceOf[_root_.scala.collection.Seq[_root_.scala.Predef.String]],
      __fieldsMap.get(__fields.get(2)).asInstanceOf[scala.Option[notibox.Notification]]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[notibox.AddNotificationRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      notibox.AddNotificationRequest(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[scala.Option[common.Context]]),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.collection.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.collection.Seq.empty),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[scala.Option[notibox.Notification]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = NotiboxProto.javaDescriptor.getMessageTypes.get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = NotiboxProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = common.Context
      case 3 => __out = notibox.Notification
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = notibox.AddNotificationRequest(
  )
  implicit class AddNotificationRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, notibox.AddNotificationRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, notibox.AddNotificationRequest](_l) {
    def ctx: _root_.scalapb.lenses.Lens[UpperPB, common.Context] = field(_.getCtx)((c_, f_) => c_.copy(ctx = Option(f_)))
    def optionalCtx: _root_.scalapb.lenses.Lens[UpperPB, scala.Option[common.Context]] = field(_.ctx)((c_, f_) => c_.copy(ctx = f_))
    def boxs: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.Seq[_root_.scala.Predef.String]] = field(_.boxs)((c_, f_) => c_.copy(boxs = f_))
    def notification: _root_.scalapb.lenses.Lens[UpperPB, notibox.Notification] = field(_.getNotification)((c_, f_) => c_.copy(notification = Option(f_)))
    def optionalNotification: _root_.scalapb.lenses.Lens[UpperPB, scala.Option[notibox.Notification]] = field(_.notification)((c_, f_) => c_.copy(notification = f_))
  }
  final val CTX_FIELD_NUMBER = 1
  final val BOXS_FIELD_NUMBER = 2
  final val NOTIFICATION_FIELD_NUMBER = 3
}
